export interface College {
    id: string;
    slug: string;
    name: string;
    location: string;
    state: string;
    rating: number;
    reviews: number;
    fees: string;
    courses: string[];
    type: "Private" | "Government" | "Deemed";
    logoUrl?: string;
    coverUrl?: string;
    tags: string[];
}

export const colleges: College[] = [
    // West Bengal
    {
        id: "1",
        slug: "institute-of-engineering-management-kolkata",
        name: "Institute of Engineering & Management (IEM)",
        location: "Salt Lake, Kolkata",
        state: "West Bengal",
        rating: 4.5,
        reviews: 1850,
        fees: "₹ 2.5L - 3.5L per year",
        courses: ["B.Tech", "M.Tech", "MBA", "BCA", "MCA"],
        type: "Private",
        tags: ["Top Ranked", "Best Placements"],
    },
    {
        id: "2",
        slug: "techno-india-salt-lake",
        name: "Techno India Main Salt Lake",
        location: "Salt Lake, Kolkata",
        state: "West Bengal",
        rating: 4.2,
        reviews: 1420,
        fees: "₹ 2L - 3L per year",
        courses: ["B.Tech", "M.Tech", "BBA", "MBA"],
        type: "Private",
        tags: ["Industry Connect"],
    },
    {
        id: "3",
        slug: "haldia-institute-of-technology",
        name: "Haldia Institute of Technology",
        location: "Haldia, West Bengal",
        state: "West Bengal",
        rating: 4.0,
        reviews: 980,
        fees: "₹ 1.8L - 2.5L per year",
        courses: ["B.Tech", "M.Tech"],
        type: "Private",
        tags: ["Research Focused"],
    },
    {
        id: "4",
        slug: "rcc-institute-of-information-technology",
        name: "RCC Institute of Information Technology",
        location: "Kolkata, West Bengal",
        state: "West Bengal",
        rating: 4.1,
        reviews: 760,
        fees: "₹ 2L - 2.8L per year",
        courses: ["B.Tech", "M.Tech", "MCA"],
        type: "Private",
        tags: ["IT Focused"],
    },
    {
        id: "5",
        slug: "jis-college-of-engineering",
        name: "JIS College of Engineering",
        location: "Kalyani, West Bengal",
        state: "West Bengal",
        rating: 4.0,
        reviews: 890,
        fees: "₹ 1.5L - 2.5L per year",
        courses: ["B.Tech", "M.Tech"],
        type: "Private",
        tags: ["Affordable"],
    },
    {
        id: "6",
        slug: "heritage-institute-of-technology",
        name: "Heritage Institute of Technology",
        location: "Kolkata, West Bengal",
        state: "West Bengal",
        rating: 4.3,
        reviews: 1150,
        fees: "₹ 2.2L - 3L per year",
        courses: ["B.Tech", "M.Tech", "MBA"],
        type: "Private",
        tags: ["Legacy Institution"],
    },
    {
        id: "7",
        slug: "techno-international-new-town",
        name: "Techno International New Town (TINT)",
        location: "New Town, Kolkata",
        state: "West Bengal",
        rating: 4.1,
        reviews: 680,
        fees: "₹ 2L - 2.8L per year",
        courses: ["B.Tech", "M.Tech"],
        type: "Private",
        tags: ["Modern Campus"],
    },
    {
        id: "8",
        slug: "netaji-subhash-engineering-college",
        name: "Netaji Subhash Engineering College",
        location: "Kolkata, West Bengal",
        state: "West Bengal",
        rating: 4.2,
        reviews: 1320,
        fees: "₹ 2L - 3L per year",
        courses: ["B.Tech", "M.Tech", "MBA"],
        type: "Private",
        tags: ["Top Ranked"],
    },
    {
        id: "9",
        slug: "meghnad-saha-institute-of-technology",
        name: "Meghnad Saha Institute of Technology (MSIT)",
        location: "Kolkata, West Bengal",
        state: "West Bengal",
        rating: 4.4,
        reviews: 1580,
        fees: "₹ 2.5L - 3.2L per year",
        courses: ["B.Tech", "M.Tech", "MCA"],
        type: "Private",
        tags: ["Best Placements", "Top Ranked"],
    },
    {
        id: "10",
        slug: "academy-of-technology",
        name: "Academy of Technology (AOT)",
        location: "Hooghly, West Bengal",
        state: "West Bengal",
        rating: 4.0,
        reviews: 720,
        fees: "₹ 1.8L - 2.5L per year",
        courses: ["B.Tech", "M.Tech"],
        type: "Private",
        tags: ["Affordable"],
    },

    // Karnataka
    {
        id: "11",
        slug: "rv-college-of-engineering-bangalore",
        name: "RV College of Engineering",
        location: "Bengaluru, Karnataka",
        state: "Karnataka",
        rating: 4.8,
        reviews: 2850,
        fees: "₹ 3.5L - 4.5L per year",
        courses: ["B.Tech", "M.Tech", "MCA"],
        type: "Private",
        tags: ["Top Ranked", "NIRF Top 100"],
    },
    {
        id: "12",
        slug: "dayananda-sagar-university",
        name: "Dayananda Sagar University",
        location: "Bengaluru, Karnataka",
        state: "Karnataka",
        rating: 4.3,
        reviews: 1920,
        fees: "₹ 3L - 4L per year",
        courses: ["B.Tech", "M.Tech", "MBA", "BBA"],
        type: "Private",
        tags: ["Multi-disciplinary"],
    },
    {
        id: "13",
        slug: "bms-college-of-engineering",
        name: "B.M.S. College of Engineering",
        location: "Bengaluru, Karnataka",
        state: "Karnataka",
        rating: 4.7,
        reviews: 2650,
        fees: "₹ 2.5L - 3.5L per year",
        courses: ["B.Tech", "M.Tech"],
        type: "Private",
        tags: ["Heritage", "Top Ranked"],
    },
    {
        id: "14",
        slug: "ramaiah-university-of-applied-sciences",
        name: "Ramaiah University of Applied Sciences",
        location: "Bengaluru, Karnataka",
        state: "Karnataka",
        rating: 4.4,
        reviews: 1780,
        fees: "₹ 3L - 4L per year",
        courses: ["B.Tech", "M.Tech", "MBA"],
        type: "Private",
        tags: ["Research Focused"],
    },
    {
        id: "15",
        slug: "pes-university-bangalore",
        name: "PES University",
        location: "Bengaluru, Karnataka",
        state: "Karnataka",
        rating: 4.6,
        reviews: 2340,
        fees: "₹ 4.5L - 6L per year",
        courses: ["B.Tech", "M.Tech", "MBA", "BBA"],
        type: "Private",
        tags: ["Top Ranked", "Best Placements"],
    },
    {
        id: "16",
        slug: "acharya-institute-of-technology",
        name: "Acharya Institute of Technology",
        location: "Bengaluru, Karnataka",
        state: "Karnataka",
        rating: 4.2,
        reviews: 1450,
        fees: "₹ 2.5L - 3.5L per year",
        courses: ["B.Tech", "M.Tech", "MBA"],
        type: "Private",
        tags: ["Industry Connect"],
    },

    // Maharashtra
    {
        id: "17",
        slug: "dr-dy-patil-vidyapeeth-pune",
        name: "Dr. D. Y. Patil Vidyapeeth",
        location: "Pune, Maharashtra",
        state: "Maharashtra",
        rating: 4.5,
        reviews: 2100,
        fees: "₹ 3.5L - 5L per year",
        courses: ["B.Tech", "M.Tech", "MBA", "Medical"],
        type: "Deemed",
        tags: ["Deemed University", "Multi-disciplinary"],
    },
    {
        id: "18",
        slug: "maharashtra-institute-of-technology",
        name: "Maharashtra Institute of Technology",
        location: "Pune, Maharashtra",
        state: "Maharashtra",
        rating: 4.6,
        reviews: 2450,
        fees: "₹ 3L - 4L per year",
        courses: ["B.Tech", "M.Tech"],
        type: "Private",
        tags: ["Top Ranked", "NIRF Top 100"],
    },
    {
        id: "19",
        slug: "symbiosis-international-university",
        name: "Symbiosis International (Deemed University)",
        location: "Pune, Maharashtra",
        state: "Maharashtra",
        rating: 4.7,
        reviews: 3200,
        fees: "₹ 4L - 6L per year",
        courses: ["B.Tech", "MBA", "Law", "Design"],
        type: "Deemed",
        tags: ["Premium", "Top Ranked"],
    },
    {
        id: "20",
        slug: "dy-patil-university-mumbai",
        name: "D.Y. Patil University",
        location: "Mumbai, Maharashtra",
        state: "Maharashtra",
        rating: 4.4,
        reviews: 1890,
        fees: "₹ 3.5L - 5L per year",
        courses: ["B.Tech", "M.Tech", "MBA", "Medical"],
        type: "Deemed",
        tags: ["Multi-disciplinary"],
    },

    // Tamil Nadu
    {
        id: "21",
        slug: "vellore-institute-of-technology",
        name: "Vellore Institute of Technology (VIT)",
        location: "Vellore, Tamil Nadu",
        state: "Tamil Nadu",
        rating: 4.8,
        reviews: 5200,
        fees: "₹ 4L - 5L per year",
        courses: ["B.Tech", "M.Tech", "MBA", "PhD"],
        type: "Deemed",
        tags: ["Top Ranked", "NIRF Top 20", "Best Placements"],
    },
    {
        id: "22",
        slug: "srm-institute-of-science-technology",
        name: "SRM Institute of Science and Technology",
        location: "Chennai, Tamil Nadu",
        state: "Tamil Nadu",
        rating: 4.7,
        reviews: 4800,
        fees: "₹ 3.5L - 5L per year",
        courses: ["B.Tech", "M.Tech", "MBA", "Medical"],
        type: "Deemed",
        tags: ["Top Ranked", "NIRF Top 50"],
    },

    // Uttarakhand
    {
        id: "23",
        slug: "upes-dehradun",
        name: "University of Petroleum and Energy Studies (UPES)",
        location: "Dehradun, Uttarakhand",
        state: "Uttarakhand",
        rating: 4.5,
        reviews: 2650,
        fees: "₹ 4L - 6L per year",
        courses: ["B.Tech", "MBA", "Law", "Design"],
        type: "Private",
        tags: ["Energy Sector Focus", "Top Placements"],
    },
    {
        id: "24",
        slug: "doon-university",
        name: "Doon University",
        location: "Dehradun, Uttarakhand",
        state: "Uttarakhand",
        rating: 4.1,
        reviews: 980,
        fees: "₹ 1L - 2L per year",
        courses: ["B.Tech", "M.Tech", "MBA", "Arts"],
        type: "Government",
        tags: ["Government", "Affordable"],
    },

    // Odisha
    {
        id: "25",
        slug: "kiit-university-bhubaneswar",
        name: "Kalinga Institute of Industrial Technology (KIIT)",
        location: "Bhubaneswar, Odisha",
        state: "Odisha",
        rating: 4.6,
        reviews: 3800,
        fees: "₹ 3.5L - 4.5L per year",
        courses: ["B.Tech", "M.Tech", "MBA", "Law", "Medical"],
        type: "Deemed",
        tags: ["Top Ranked", "NIRF Top 50", "Best Campus"],
    },
    {
        id: "26",
        slug: "soa-university-bhubaneswar",
        name: "Siksha 'O' Anusandhan (SOA) University",
        location: "Bhubaneswar, Odisha",
        state: "Odisha",
        rating: 4.5,
        reviews: 2450,
        fees: "₹ 3L - 4L per year",
        courses: ["B.Tech", "M.Tech", "MBA", "Medical", "Dental"],
        type: "Deemed",
        tags: ["Multi-disciplinary", "Research Focused"],
    },
    {
        id: "27",
        slug: "cv-raman-global-university",
        name: "C. V. Raman Global University",
        location: "Bhubaneswar, Odisha",
        state: "Odisha",
        rating: 4.2,
        reviews: 1320,
        fees: "₹ 2.5L - 3.5L per year",
        courses: ["B.Tech", "M.Tech", "MBA"],
        type: "Private",
        tags: ["Growing Institution"],
    },
    {
        id: "28",
        slug: "silicon-university-bhubaneswar",
        name: "Silicon University",
        location: "Bhubaneswar, Odisha",
        state: "Odisha",
        rating: 4.3,
        reviews: 1680,
        fees: "₹ 2.5L - 3.5L per year",
        courses: ["B.Tech", "M.Tech", "MCA"],
        type: "Private",
        tags: ["IT Focused", "Good Placements"],
    },
];

// Group colleges by state
export const collegesByState = colleges.reduce((acc, college) => {
    if (!acc[college.state]) {
        acc[college.state] = [];
    }
    acc[college.state].push(college);
    return acc;
}, {} as Record<string, College[]>);

// Company contact information
export const companyInfo = {
    name: "Akash Talks",
    tagline: "Direct Admission in B.Tech",
    phones: ["+91 9874878782", "+91 8825352628"],
    email: "admissions@akashtalks.com",
    youtube: "https://www.youtube.com/@akash_talks",
    address: {
        line1: "GN-34/1, Aurora Water Front, Unit 21",
        line2: "11th Floor, Sector V",
        city: "Salt Lake, Kolkata",
        state: "West Bengal",
        pincode: "700091",
        full: "GN-34/1, Aurora Water Front, Unit 21, 11th Floor, Sector V, Salt Lake, Kolkata - 700091"
    },
    services: [
        "Direct B.Tech Admissions",
        "College Selection Guidance",
        "Career Counseling",
        "Application Support",
        "Scholarship Assistance"
    ],
    states: ["West Bengal", "Karnataka", "Maharashtra", "Tamil Nadu", "Uttarakhand", "Odisha"]
};
